# Generated by Django 5.0.7 on 2024-08-29 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
